import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script src="/browser.js" strategy="beforeInteractive" />
        {children}
      </body>
    </html>
  );
}
